// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxgiAY78BCC2yi0rZ03asxWhmmFNfFjaI',
    appId: '1:665486927950:web:0bc531e6e5767c9e7bfb1f',
    messagingSenderId: '665486927950',
    projectId: 'brenbox-403d2',
    authDomain: 'brenbox-403d2.firebaseapp.com',
    storageBucket: 'brenbox-403d2.firebasestorage.app',
    measurementId: 'G-KPHMCPV8K1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtrA_1x2R_p4fR934ik5eJ3ifb0oxg5Uc',
    appId: '1:665486927950:android:c9416060c90221bc7bfb1f',
    messagingSenderId: '665486927950',
    projectId: 'brenbox-403d2',
    storageBucket: 'brenbox-403d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZS11WZB8QqYjfnstKZkwhvCl_J-LRUuw',
    appId: '1:665486927950:ios:bb94a6fb6f37847f7bfb1f',
    messagingSenderId: '665486927950',
    projectId: 'brenbox-403d2',
    storageBucket: 'brenbox-403d2.firebasestorage.app',
    iosBundleId: 'com.example.brenboxApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZS11WZB8QqYjfnstKZkwhvCl_J-LRUuw',
    appId: '1:665486927950:ios:bb94a6fb6f37847f7bfb1f',
    messagingSenderId: '665486927950',
    projectId: 'brenbox-403d2',
    storageBucket: 'brenbox-403d2.firebasestorage.app',
    iosBundleId: 'com.example.brenboxApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxgiAY78BCC2yi0rZ03asxWhmmFNfFjaI',
    appId: '1:665486927950:web:9a3e5705e4c9d6a97bfb1f',
    messagingSenderId: '665486927950',
    projectId: 'brenbox-403d2',
    authDomain: 'brenbox-403d2.firebaseapp.com',
    storageBucket: 'brenbox-403d2.firebasestorage.app',
    measurementId: 'G-HW2RL9L6XS',
  );
}
